// Generated by Tools/merivus/flight_control_research/candidate.py; do not edit.
// Candidate SHA-256: 99a0b636066297ce795955f0bea3d6852ce37d13f10b9254d2137b7953a7ca5b
static constexpr Node nodes[] = {
	{Op::VelocityError, -1, -1, 0.0f, 0.0f, 0.0f},
	{Op::VelocityGain, 0, -1, 0.15f, 0.15f, 0.0f},
	{Op::AccelerationResidual, -1, -1, 0.0f, 0.0f, 0.0f},
	{Op::LowpassAcceleration, 2, -1, 0.12f, 0.0f, 0.0f},
	{Op::LowpassAcceleration, 2, -1, 1.5f, 0.0f, 0.0f},
	{Op::AccelerationGain, 3, -1, -0.15f, -0.15f, 0.0f},
	{Op::AccelerationGain, 4, -1, 0.15f, 0.15f, 0.0f},
	{Op::AddAcceleration, 5, 6, 0.0f, 0.0f, 0.0f},
	{Op::AddAcceleration, 1, 7, 0.0f, 0.0f, 0.0f},
	{Op::LimitAcceleration, 8, -1, 0.35f, 0.35f, 0.05f},
};
static constexpr unsigned node_count = 10;
static constexpr unsigned output_node = 9;
static constexpr float maximum_correction = 0.5f;
