// Generated by Tools/merivus/flight_control_research/candidate.py; do not edit.
// Candidate SHA-256: 4c058ed10330a63f58ee53f4c2492872e2f3ea1708146929dcf4b10fb33eb1db
static constexpr Node nodes[] = {
	{Op::AccelerationResidual, -1, -1, 0.0f, 0.0f, 0.0f},
	{Op::LowpassAcceleration, 0, -1, 0.35f, 0.0f, 0.0f},
	{Op::AccelerationGain, 1, -1, -0.3f, -0.3f, -0.2f},
	{Op::LimitAcceleration, 2, -1, 0.8f, 0.8f, 0.5f},
};
static constexpr unsigned node_count = 4;
static constexpr unsigned output_node = 3;
static constexpr float maximum_correction = 1.0f;
